# What is the purpose of the 'finally' block in a try-except statement?

print(1 * 4 // 2 ** 3)